apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: tejas299/cc_client:latest   # Replace this with your desired image
    command:
    - "/bin/sh"
    - "-c"
    - |
      cp /Backup/token.pickle /Tokens/token.pickle &&
      cp /Backup/Script.py /Tokens/Script.py &&
      sleep infinity
    volumeMounts:
    - name: my-pvc
      mountPath: /Tokens
    volumeMounts:
    - name: app-file
      mountPath: /Backup/App
  volumes:
  - name: my-pvc
    persistentVolumeClaim:
      claimName: my-pvc  # Use the same PVC name as before
  - name: app-file
    persistentVolumeClaim:
      claimName: app-file

